### ISSUE TITLE
question: Error during seemingly correct construction of `CommandContinuationRequest`

### ISSUE THREAD

**Issue by jakoschiko** [duesee/imap-flow#170]
When writing a test, I used this very common text for accepting literals:

```rust
setup.server_flow_options.literal_accept_text = Text::unvalidated("moah");
```

Unfortunately this caused a panic inside of `imap-flow`:

```
thread 'command_with_literals_larger_than_max_command_size' panicked at src/server.rs:299:38:
called `Result::unwrap()` on an `Err` value: Ambiguity
```

This is the mentioned `unwrap`:

```rust
// Inform the client that the literal was accepted.

// Unwrap: This should never fail because the text is not Base64.
let cont = CommandContinuationRequest::basic(
    None,
    self.options.literal_accept_text.clone(),
)
.unwrap();
self.send_response_state.enqueue_response(
    None,
    Response::CommandContinuationRequest(cont),
);
```

**Comment by duesee** [comment]
IMAP has an ambiguity. If you receive ...

```
+ moah
```

... it's unclear wheather you mean "woah" as text or [9a, 86, a1] (`b64decode("woah")`). It can be both. Thus, I prevented the construction of ambiguous messages. Normally, you should not run into this because `try_from` would fail. But... `unvalidated` is unfortunate.

Seeing you running into this, I strongly feel we should redesign that in imap-codec.
