### ISSUE TITLE
question: How to use our handles?

### ISSUE THREAD

**Issue by duesee** [duesee/imap-flow#44]
> Hmm, something like that is worth a try. Whether it's a good idea to put the command inside the handle is still up for discussion.

_Originally posted by @jakoschiko in https://github.com/duesee/imap-flow/pull/43#discussion_r1364579272_

* question: Put `{Command/Response}` in `{Command/Response}Handle`?
* question: How to use the handle, actually?

**Comment by jakoschiko** [comment]
How a real client application would use the handle:

- The client enqueues a big command and stores the handle inside a set
- While the set is not empty a "Sending in progress" animation is displayed
- While the sending is in progress, the client might enqueue other commands and receive other server responses
- If the command was sent successfully, the client gets the `CommandSent`, removes the handle from the set and the animation stops because the set is not empty
- If the command was not sent successfully (e.g. the literal is too big and was rejected), then the Client also removes the handle from the set and displays an error with more details
  - Note that this is currently not possible because the client is not informed that the literal was rejected. We probably need to emit another `ClientFlowEvent` in `ClientFlow::maybe_abort_command`.

The handle is better than the tag because its Eq and Hash is cheaper and ClientFlow can ensure that it's unique.

So what we need to do:
- Document the purpose of the handle what is guaranteed by the implementation of `imap-flow`
- Make sure that a proper event with the handle is emitted in all cases (success and failure)
- Put all information that is (cheaply) available inside the event that contains the handle (e.g. the command that was enqueued) so that it can be easily used for logging/debugging/error messages

**Comment by duesee** [comment]
Thanks! Yeah. On this level this is clear to me. And it makes total sense! Where it gets complicated are the IMAP semantics. Do we `push` every response we receive that comes *before* the `CommandSent` event into an `unsolicited` vector when implementing, e.g., a `client.login(user, pass)` method?

> Note that this is currently not possible because the client is not informed that the literal was rejected. We probably need to emit another ClientFlowEvent in ClientFlow::maybe_abort_command.

On the surface, this should already worj. When a literal is rejected, it is done through a "normal" tagged `NO` response. Thus, handling is done on the consumer site. But... I'm just playing with the demo and imap-flow doesn't implement this logic as it seems. We'll need to investigate.

**Comment by jakoschiko** [comment]
@duesee: #56 improved the documentation for the handles. Can we close this issue?
